services:
  - type: web
    name: edutrack-api
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate
    startCommand: node src/server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://edutrack-ten-inky.vercel.app
      - key: CAMPUS_LAT
        value: "17.411"
      - key: CAMPUS_LNG
        value: "78.529"
      - key: PORT
        value: "10000"